INSERT INTO STUDENT VALUES(1,'nowakjan','Jan',112233,'Nowak')
INSERT INTO STUDENT VALUES(2,'kowalskajoanna','Joanna',223344,'Kowalska')
INSERT INTO STUDENT VALUES(3,'kozioljedrzej','Jedrzej',123456,'Koziol')
INSERT INTO STUDENT VALUES(4,'szatanszatan','Szatan',100666,'Szatanski')
INSERT INTO STUDENT VALUES(5,'tepyburak','Burak',100100,'Buraczany')
INSERT INTO GRUPA VALUES(1,'Grupa I')
INSERT INTO GRUPA VALUES(2,'Grupa II')
INSERT INTO GRUPA VALUES(3,'Lektorat B2')
INSERT INTO GRUPA VALUES(4,'Lektorat C1')
INSERT INTO GRUPA VALUES(5,'F Scala gr.1')
INSERT INTO GRUPA VALUES(6,'F scala gr.2')
INSERT INTO PROWADZACY VALUES(1,'p.111','Andrzej','apolak','Polak','haslo','inf.ug.edu.pl/~apolak')
INSERT INTO PROWADZACY VALUES(2,'p.222','Jaros³aw','jnowakowski','Nowakowski','haslo','inf.ug.edu.pl')
INSERT INTO PROWADZACY VALUES(3,'p. -1','Kazimierz','ksienarobil','Sienarobil','haslo','delta.univ.gda.pl/~k-sienarobil')
INSERT INTO PROWADZACY VALUES(4,'p. 54','Gaal','ganonim','Anonim','haslo','inf.ug.edu.pl/~anonim')
INSERT INTO PRZEDMIOT VALUES(1,'Laboratorium','Projekt Zespo³owy')
INSERT INTO PRZEDMIOT VALUES(2,'Æwiczenia','Matematyka dyskretna')
INSERT INTO PRZEDMIOT VALUES(3,'Laboratorium','Serwery Baz Danych')
INSERT INTO PRZEDMIOT VALUES(4,'Laboratorium','Fizyka niedyskretna')
INSERT INTO PRZEDMIOT VALUES(5,'Æwiczenia','Algebra Liniowa')
INSERT INTO PRZEDMIOT VALUES(6,'Æwiczenia','Analiza Matematyczna')
INSERT INTO PRZEDMIOT VALUES(7,'Labolatorum','F Scala')
INSERT INTO PRZEDMIOT VALUES(8,'Laboratorium','Picie piwa pod p³otem')
INSERT INTO PRZEDMIOT VALUES(9,'Æwiczenia Praktyczne','Destylacja Filtracja Rozk³ad')
insert into admin values(1,'admin','admin')